### ISSUE TITLE
Consider upgrade `pymodbus` to version 3.2.2

### ISSUE THREAD

**Issue by cfreire** [gavinying/modpoll#12]
Hello @gavinying 
Please consider upgrading `pymodbus` to version 3.2.2.
Reading https://github.com/pymodbus-dev/pymodbus/blob/dev/API_changes.rst, minor changes will be necessary in code. 
Unless you have other plans, like waitting for `3.3`for FOSS and function callbacks.
Many thanks

**Comment by gavinying** [comment]
Updated, also fixed some issues in example config file. please check the latest version `0.5.3`. 
Tested with pymodbus v3.2.2, and it shall also work for v3.3 according to their current plan of API changes.
