### ISSUE TITLE
Publish timestamp along with data

### ISSUE THREAD

**Issue by dakhnod** [gavinying/modpoll#53]
Is there an option to publish the timestamp of acquisition along with the data?

If QOS>0 is selected and there is an MQTT outage, the messages should be buffered, I think. In that scenario, it would make sense to have a timestamp in every message...

**Comment by gavinying** [comment]
Hi @dakhnod, have you tried "--timestamp" argument? type `modpoll -h` or check [here](https://gavinying.github.io/modpoll/usage.html#Named%20Arguments) for details.

**Comment by dakhnod** [comment]
Thanks!
