### ISSUE TITLE
enhancement: display a better understandable error message

### ISSUE THREAD

**Issue by mi-hol** [gavinying/modpoll#76]
Maybe a better understandable error message (including the string) could be displayed?

The reason for error is a wrong register address or length of string in configuration
```
modpoll\modbus_task.py", line 172, in _decode_and_update_reference
    decoder.decode_string(ref.ref_width * 2).decode("utf-8").rstrip("\x00")
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd7 in position 8: invalid continuation byte
```

**Comment by gavinying** [comment]
thanks for your suggestion, will take it into consideration.

**Comment by mi-hol** [comment]
Thanks for implementing an improvement!
When will the new version 1.4.1 become available for download?

**Comment by mi-hol** [comment]
> When will the new version 1.4.1 become available for download?

@gavinying may I kindly ask what is holding up merging of PR #78  to get the fix released?

**Comment by gavinying** [comment]
It will be released soon, just to avoid upgrading during holiday seasons:)

**Comment by gavinying** [comment]
[v1.4.1](https://github.com/gavinying/modpoll/releases/tag/v1.4.1)  has been released. Feel free to download.
